server:
  port: 8080
  error:
    include-stacktrace: never

mybatis:
#  config-location: classpath:mybatis-config.xml
  mapper-locations:
    - classpath:mapper/**/*.xml

springdoc:
  packages-to-scan: com.bmp.dts
  swagger-ui:
    enabled: true
  api-docs:
    path: /v3/api-docs
  cache:
    disabled: true

spring:
  application:
    name: API WMS
  profiles:
    group:
      local: local-api, swagger-ui
      dev: dev-api
      prod: prod-api
      stg: stg-api

---
spring:
  config:
    activate:
      on-profile: local-api
    import: classpath:local-api.yml

---
spring:
  config:
    activate:
      on-profile: dev-api
    import: classpath:dev-api.yml

---
spring:
  config:
    activate:
      on-profile: stg-api
    import: classpath:stg-api.yml

---
spring:
  config:
    activate:
      on-profile: prod-api
    import: classpath:prod-api.yml
