spring:
  datasource:
    url: jdbc:postgresql://211.219.112.253:51113/sbp_db
    username: sbpuser
    password: sbpRole12!@
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.springframework.jdbc.datasource: debug
    com:
      bmp:
        wms: debug
  config: classpath:logback-local.xml


