spring:
  datasource:
    url: jdbc:postgresql://211.219.112.253:23013/bms
    username: bms
    password: bms01
    driver-class-name: org.postgresql.Driver

logging:
#  file:
#    path: /home/cnms/log
#    filename: stg_log
  level:
    root: info
    com:
      bmp:
        wms: debug
  config: classpath:logback-stg.xml

#jwt:
#  secret: n674pjdp2bcp3shuu5hsvxsxdb3yusmzlmy8jkybq2dos2om0avgn108nc0yl23t
#  token-valid-seconds: 600
#
#jasypt:
#  encryptor:
#    bean: jasyptStringEncryptor
#
#mybatis:
#  mapper-locations:
#    - classpath:mapper/**/*.xml
#
#springdoc:
#  packages-to-scan: com.bmp.cnms
#  swagger-ui:
#    path: swagger-ui.html
#    enabled: false  # Swagger UI를 비활성화합니다.
#  api-docs:
#    path: /v3/api-docs
#  cache:
#    disabled: true
